# Generated by Django 5.0.4 on 2024-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmazonReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("rating", models.IntegerField()),
                ("author", models.CharField(max_length=10)),
                ("reviewed_date", models.DateField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
