# Generated by Django 5.0.4 on 2024-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("asin", models.CharField(default="", max_length=20)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, max_length=5)),
                ("domain", models.CharField(blank=True, max_length=20)),
                ("productUrl", models.CharField(blank=True, max_length=100)),
                ("price", models.FloatField(blank=True)),
                ("reviews", models.IntegerField(blank=True)),
                ("ratings", models.FloatField(blank=True)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
